### ISSUE TITLE
Disappearing cockpit and broken model.

### ISSUE THREAD

**Issue by B-don-don** [TotallyRealElonMusk/GeoFS-Extra-Maritime-Structures#5]
This plugin is awesome, but when i go to the f-16, the cockpit does not load up, it freezes, then when I go to reset the camera, it doesn't show anything.

**Comment by TotallyRealElonMusk** [comment]
This should not be caused by the addon directly. Yet, it might be a performance issue, as the addon is very heavy. If such is the case, then it can't change anything. What are your computer specs?

**Comment by kolos26** [comment]
The cockpits are currently broken in geofs. When you change to cockpit in planes using a separate cockpit model (the f16 is one of them), the game crashes because it fails to load the model. So it's not because of the addon or the computer.

**Comment by TotallyRealElonMusk** [comment]
its fixed, finally. the handler code was not updated, and thus was causing issues
